### ISSUE TITLE
SyntaxError: Unexpected token '? in serverless compose

### ISSUE THREAD

**Issue by vikashaw** [serverless/compose#102]
While using serverless compose and deploying changes, I have encountered the below error - 

home/vik/node_modules/@serverless/compose/src/render-help.js:63
    Object.entries(command.options ?? {}).forEach(([key, desc]) => {
                                    ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (home/vik/node_modules/@serverless/compose/src/index.js:9:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

Using serverless version  - 3.15.2

**Comment by pgrzesik** [comment]
Hey @vikashaw - what version of Node are you using? Could you upgrade to at least node 14 for now to get rid of this issue? We will ensure that Compose is well supported on v12 as well.

**Comment by vikashaw** [comment]
> Hey @vikashaw - what version of Node are you using? Could you upgrade to at least node 14, for now, to get rid of this issue? We will ensure that Compose is well supported on v12 as well.

Ok. Thanks

**Comment by pgrzesik** [comment]
It will be fixed with the next release - I'm closing this ticket
