### ISSUE TITLE
Serverless V4: Unrecognized option "service"

### ISSUE THREAD

**Issue by jameshalsall** [serverless/compose#193]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When running deploy from the root and specifying `--service` we get an error that it's an unrecognised option.

Running SLS v4.1.19 and 1.3.0 of compose.

### Service configuration (serverless-compose.yml) content

```yaml
N/A
```

### Command name and used flags

sls deploy --stage staging --service platform

### Command output

```shell
$ /Users/jameshalsall/Code/foo/node_modules/.bin/sls deploy --stage staging --service platform


✖ Unrecognized option "service". Run "serverless deploy --help" for a list of all available options.
ServerlessError2: Unrecognized option "service". Run "serverless deploy --help" for a list of all available options.
    at ensure_supported_command_default (file:///Users/jameshalsall/.serverless/releases/4.1.19/package/dist/sf-core.js:865:2605)
    at route (file:///Users/jameshalsall/.serverless/releases/4.1.19/package/dist/sf-core.js:920:14171)
    at Object.run2 [as run] (file:///Users/jameshalsall/.serverless/releases/4.1.19/package/dist/sf-core.js:920:16708)
    at async run3 (file:///Users/jameshalsall/.serverless/releases/4.1.19/package/dist/sf-core.js:920:17962)
```

**Comment by czubocha** [comment]
Hey @jameshalsall, thanks for reporting this. Sorry for the inconvenience - we’re aware of the issue and are working on a fix. I’ll let you know once it’s released.
